name: flutter_clean_architecture
description: This is a simple for Clean Architecture using the Provider Pattern

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: '>=2.0.0'

# If override conflict depends library version
#dependency_overrides:

dependencies:
  flutter:
    sdk: flutter

  # For data class
  equatable: ^2.0.3

  # Resource localizations
  flutter_localizations:
    sdk: flutter

  # For Design Pattern
  flutter_hooks: ^0.18.1
  hooks_riverpod: ^2.1.3

  # For Networking
  dio: ^4.0.3
  retrofit: ^3.0.0

  # Json serializable & model
  json_annotation: ^4.3.0
  freezed_annotation: ^2.0.3
  enum_to_string: ^2.0.1

  # Platform information
  package_info: ^2.0.2

  # Default icon for widget
  cupertino_icons: ^1.0.3

  # Shared Preferences
  # shared_preferences: ^2.0.6
  # Change S.Prefs by Hive
  hive: ^2.2.0
  hive_flutter: ^1.1.0

  # Support for design
  flutter_svg: ^2.0.0+1

  # Image Cached
  cached_network_image: ^3.0.0

  # Flare
  flare_flutter: ^3.0.2

  # Lib for custom view
  carousel_slider: ^4.0.0

  # Toast view
  fluttertoast: ^8.1.2

  #otp verify
  pin_code_fields: ^7.4.0

  # fire base
  firebase_core: ^2.4.1

  # intro slider
  card_swiper: ^2.0.4

  # responsive view
  flutter_screenutil: ^5.6.1

  # auto size text
  auto_size_text: ^3.0.0

  #loging api
  pretty_dio_logger: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Data class
  freezed: ^2.0.3+1

  # Generate object
  hive_generator: any

  # Auto generate some files
  build_runner: ^2.0.4
  #  build_runner: ^1.11.5
  flutter_gen_runner: ^5.2.0
  json_serializable: ^6.0.1

  # retrofit
  retrofit_generator: ^4.0.1

  # unit test & calculate coverage
  mockito: ^5.0.16

  # Lint when build
  flutter_lints: ^2.0.1

# Config generate when build
flutter_gen:
  output: lib/gen/
  line_lenght: 160
  null_safety: true

  integrations:
    flutter_svg: true
    flare_flutter: true

  assets:
    enabled: true

  fonts:
    enabled: true

  colors:
    enabled: true
    inputs:
      - assets/color/colors.xml

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/

  fonts:
    - family: SVN-Gilroy
      fonts:
        - asset: assets/fonts/SVN-Gilroy-Thin.otf
          weight: 100
        - asset: assets/fonts/SVN-Gilroy-Thin-Italic.otf
          weight: 100
          style: italic
        - asset: assets/fonts/SVN-Gilroy-Xlight.otf
          weight: 200
        - asset: assets/fonts/SVN-Gilroy-Xlight-Italic.otf
          weight: 200
          style: italic
        - asset: assets/fonts/SVN-Gilroy-Light.otf
          weight: 300
        - asset: assets/fonts/SVN-Gilroy-Light-Italic.otf
          weight: 300
          style: italic
        - asset: assets/fonts/SVN-Gilroy-Regular.otf
          weight: 400
        - asset: assets/fonts/SVN-Gilroy-Italic.otf
          weight: 400
          style: italic
        - asset: assets/fonts/SVN-Gilroy-Medium.otf
          weight: 500
        - asset: assets/fonts/SVN-Gilroy-Medium-Italic.otf
          weight: 500
          style: italic
        - asset: assets/fonts/SVN-Gilroy-SemiBold.otf
          weight: 600
        - asset: assets/fonts/SVN-Gilroy-SemiBold-Italic.otf
          weight: 600
        - asset: assets/fonts/SVN-Gilroy-Bold.otf
          weight: 700
        - asset: assets/fonts/SVN-Gilroy-Bold-Italic.otf
          weight: 700
          style: italic
        - asset: assets/fonts/SVN-Gilroy-XBold.otf
          weight: 800
        - asset: assets/fonts/SVN-Gilroy-XBold-Italic.otf
          weight: 800
          style: italic
        - asset: assets/fonts/SVN-Gilroy-Black.otf
          weight: 900
        - asset: assets/fonts/SVN-Gilroy-Black-Italic.otf
          weight: 900
          style: italic


